/* 
 * Payment Request
 *
 * A payment request is a request for payment (partial or full) of an invoice. This API provides methods to create or update a payment request, or view a payment request by ID.
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace SapConcurApiClient.PaymentRequestModels
{
    /// <summary>
    /// PaymentRequestLineItemPut
    /// </summary>
    [DataContract]
    public partial class PaymentRequestLineItemPut : IEquatable<PaymentRequestLineItemPut>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestLineItemPut" /> class.
        /// </summary>
        /// <param name="action">The operation(INSERT/UPDATE/DELETE) to be performed on the Line Item..</param>
        /// <param name="allocations">allocations.</param>
        /// <param name="amountWithoutVat">The net amount of the line item (excluding VAT)..</param>
        /// <param name="custom01">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom02">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom03">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom04">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom05">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom06">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom07">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom08">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom09">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom10">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom11">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom12">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom13">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom14">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom15">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom16">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom17">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom18">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom19">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="custom20">The details from the Custom fields. These may not have data, depending on configuration..</param>
        /// <param name="description">Brief overview of the good or service ordered..</param>
        /// <param name="expenseTypeCode">A code which indicates the Expense Type for the Line Item..</param>
        /// <param name="itemCode">Represents the item code (the unique code a vendor assigns to a good or code a vendor assigns to a good or service to identify it)..</param>
        /// <param name="lineItemID">Line Item ID of the Payment Request..</param>
        /// <param name="purchaseOrderNumber">Purchase Order that is associated to the Line Item ..</param>
        /// <param name="quantity">Total number of goods or services ordered..</param>
        /// <param name="shipFromPostalCode">The postal code the good or service was shipped from..</param>
        /// <param name="shipToPostalCode">The postal code the good or service will be shipped to..</param>
        /// <param name="supplierPartId">The unique identifier provided by the supplier that is associated with the good or service..</param>
        /// <param name="tax">The tax associated with the line item..</param>
        /// <param name="taxCode">The Tax Code  assigned for the Line Item, based on the Tax Setting..</param>
        /// <param name="taxCode2">The Tax Code 2 assigned for the Line Item, based on the Tax Setting..</param>
        /// <param name="taxCode3">The Tax Code 3 assigned for the Line Item, based on the Tax Setting..</param>
        /// <param name="taxCode4">The Tax Code 4 assigned for the Line Item, based on the Tax Setting..</param>
        /// <param name="unitOfMeasure">The code for the measurement unit used to quantify the good or service. Use GET /invoice/localizeddata to look up codes and descriptions..</param>
        /// <param name="unitPrice">The cost for a single unit of the line item good or service..</param>
        /// <param name="vatAmount">The amount of VAT 1 included in the line item total..</param>
        /// <param name="vatAmountFour">The amount of VAT 4 included in the line item total..</param>
        /// <param name="vatAmountThree">The amount of VAT 3 included in the line item total..</param>
        /// <param name="vatAmountTwo">The amount of VAT 2 included in the line item total..</param>
        /// <param name="vatRate">The VAT rate 1 applied to the net line item total..</param>
        /// <param name="vatRateFour">The VAT rate 4 applied to the net line item total..</param>
        /// <param name="vatRateThree">The VAT rate 3 applied to the net line item total..</param>
        /// <param name="vatRateTwo">The VAT rate 2 applied to the net line item total..</param>
        public PaymentRequestLineItemPut(string action = default(string), PaymentRequestAllocationPostPut allocations = default(PaymentRequestAllocationPostPut), string amountWithoutVat = default(string), string custom01 = default(string), string custom02 = default(string), string custom03 = default(string), string custom04 = default(string), string custom05 = default(string), string custom06 = default(string), string custom07 = default(string), string custom08 = default(string), string custom09 = default(string), string custom10 = default(string), string custom11 = default(string), string custom12 = default(string), string custom13 = default(string), string custom14 = default(string), string custom15 = default(string), string custom16 = default(string), string custom17 = default(string), string custom18 = default(string), string custom19 = default(string), string custom20 = default(string), string description = default(string), string expenseTypeCode = default(string), string itemCode = default(string), string lineItemID = default(string), string purchaseOrderNumber = default(string), string quantity = default(string), string shipFromPostalCode = default(string), string shipToPostalCode = default(string), string supplierPartId = default(string), string tax = default(string), string taxCode = default(string), string taxCode2 = default(string), string taxCode3 = default(string), string taxCode4 = default(string), string unitOfMeasure = default(string), string unitPrice = default(string), string vatAmount = default(string), string vatAmountFour = default(string), string vatAmountThree = default(string), string vatAmountTwo = default(string), string vatRate = default(string), string vatRateFour = default(string), string vatRateThree = default(string), string vatRateTwo = default(string))
        {
            this.Action = action;
            this.Allocations = allocations;
            this.AmountWithoutVat = amountWithoutVat;
            this.Custom01 = custom01;
            this.Custom02 = custom02;
            this.Custom03 = custom03;
            this.Custom04 = custom04;
            this.Custom05 = custom05;
            this.Custom06 = custom06;
            this.Custom07 = custom07;
            this.Custom08 = custom08;
            this.Custom09 = custom09;
            this.Custom10 = custom10;
            this.Custom11 = custom11;
            this.Custom12 = custom12;
            this.Custom13 = custom13;
            this.Custom14 = custom14;
            this.Custom15 = custom15;
            this.Custom16 = custom16;
            this.Custom17 = custom17;
            this.Custom18 = custom18;
            this.Custom19 = custom19;
            this.Custom20 = custom20;
            this.Description = description;
            this.ExpenseTypeCode = expenseTypeCode;
            this.ItemCode = itemCode;
            this.LineItemID = lineItemID;
            this.PurchaseOrderNumber = purchaseOrderNumber;
            this.Quantity = quantity;
            this.ShipFromPostalCode = shipFromPostalCode;
            this.ShipToPostalCode = shipToPostalCode;
            this.SupplierPartId = supplierPartId;
            this.Tax = tax;
            this.TaxCode = taxCode;
            this.TaxCode2 = taxCode2;
            this.TaxCode3 = taxCode3;
            this.TaxCode4 = taxCode4;
            this.UnitOfMeasure = unitOfMeasure;
            this.UnitPrice = unitPrice;
            this.VatAmount = vatAmount;
            this.VatAmountFour = vatAmountFour;
            this.VatAmountThree = vatAmountThree;
            this.VatAmountTwo = vatAmountTwo;
            this.VatRate = vatRate;
            this.VatRateFour = vatRateFour;
            this.VatRateThree = vatRateThree;
            this.VatRateTwo = vatRateTwo;
        }

        /// <summary>
        /// The operation(INSERT/UPDATE/DELETE) to be performed on the Line Item.
        /// </summary>
        /// <value>The operation(INSERT/UPDATE/DELETE) to be performed on the Line Item.</value>
        [DataMember(Name = "Action", EmitDefaultValue = false)]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets Allocations
        /// </summary>
        [DataMember(Name = "Allocations", EmitDefaultValue = false)]
        public PaymentRequestAllocationPostPut Allocations { get; set; }

        /// <summary>
        /// The net amount of the line item (excluding VAT).
        /// </summary>
        /// <value>The net amount of the line item (excluding VAT).</value>
        [DataMember(Name = "AmountWithoutVat", EmitDefaultValue = false)]
        public string AmountWithoutVat { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom01", EmitDefaultValue = false)]
        public string Custom01 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom02", EmitDefaultValue = false)]
        public string Custom02 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom03", EmitDefaultValue = false)]
        public string Custom03 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom04", EmitDefaultValue = false)]
        public string Custom04 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom05", EmitDefaultValue = false)]
        public string Custom05 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom06", EmitDefaultValue = false)]
        public string Custom06 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom07", EmitDefaultValue = false)]
        public string Custom07 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom08", EmitDefaultValue = false)]
        public string Custom08 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom09", EmitDefaultValue = false)]
        public string Custom09 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom10", EmitDefaultValue = false)]
        public string Custom10 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom11", EmitDefaultValue = false)]
        public string Custom11 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom12", EmitDefaultValue = false)]
        public string Custom12 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom13", EmitDefaultValue = false)]
        public string Custom13 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom14", EmitDefaultValue = false)]
        public string Custom14 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom15", EmitDefaultValue = false)]
        public string Custom15 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom16", EmitDefaultValue = false)]
        public string Custom16 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom17", EmitDefaultValue = false)]
        public string Custom17 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom18", EmitDefaultValue = false)]
        public string Custom18 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom19", EmitDefaultValue = false)]
        public string Custom19 { get; set; }

        /// <summary>
        /// The details from the Custom fields. These may not have data, depending on configuration.
        /// </summary>
        /// <value>The details from the Custom fields. These may not have data, depending on configuration.</value>
        [DataMember(Name = "Custom20", EmitDefaultValue = false)]
        public string Custom20 { get; set; }

        /// <summary>
        /// Brief overview of the good or service ordered.
        /// </summary>
        /// <value>Brief overview of the good or service ordered.</value>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// A code which indicates the Expense Type for the Line Item.
        /// </summary>
        /// <value>A code which indicates the Expense Type for the Line Item.</value>
        [DataMember(Name = "ExpenseTypeCode", EmitDefaultValue = false)]
        public string ExpenseTypeCode { get; set; }

        /// <summary>
        /// Represents the item code (the unique code a vendor assigns to a good or code a vendor assigns to a good or service to identify it).
        /// </summary>
        /// <value>Represents the item code (the unique code a vendor assigns to a good or code a vendor assigns to a good or service to identify it).</value>
        [DataMember(Name = "ItemCode", EmitDefaultValue = false)]
        public string ItemCode { get; set; }

        /// <summary>
        /// Line Item ID of the Payment Request.
        /// </summary>
        /// <value>Line Item ID of the Payment Request.</value>
        [DataMember(Name = "LineItemID", EmitDefaultValue = false)]
        public string LineItemID { get; set; }

        /// <summary>
        /// Purchase Order that is associated to the Line Item .
        /// </summary>
        /// <value>Purchase Order that is associated to the Line Item .</value>
        [DataMember(Name = "PurchaseOrderNumber", EmitDefaultValue = false)]
        public string PurchaseOrderNumber { get; set; }

        /// <summary>
        /// Total number of goods or services ordered.
        /// </summary>
        /// <value>Total number of goods or services ordered.</value>
        [DataMember(Name = "Quantity", EmitDefaultValue = false)]
        public string Quantity { get; set; }

        /// <summary>
        /// The postal code the good or service was shipped from.
        /// </summary>
        /// <value>The postal code the good or service was shipped from.</value>
        [DataMember(Name = "ShipFromPostalCode", EmitDefaultValue = false)]
        public string ShipFromPostalCode { get; set; }

        /// <summary>
        /// The postal code the good or service will be shipped to.
        /// </summary>
        /// <value>The postal code the good or service will be shipped to.</value>
        [DataMember(Name = "ShipToPostalCode", EmitDefaultValue = false)]
        public string ShipToPostalCode { get; set; }

        /// <summary>
        /// The unique identifier provided by the supplier that is associated with the good or service.
        /// </summary>
        /// <value>The unique identifier provided by the supplier that is associated with the good or service.</value>
        [DataMember(Name = "SupplierPartId", EmitDefaultValue = false)]
        public string SupplierPartId { get; set; }

        /// <summary>
        /// The tax associated with the line item.
        /// </summary>
        /// <value>The tax associated with the line item.</value>
        [DataMember(Name = "Tax", EmitDefaultValue = false)]
        public string Tax { get; set; }

        /// <summary>
        /// The Tax Code  assigned for the Line Item, based on the Tax Setting.
        /// </summary>
        /// <value>The Tax Code  assigned for the Line Item, based on the Tax Setting.</value>
        [DataMember(Name = "TaxCode", EmitDefaultValue = false)]
        public string TaxCode { get; set; }

        /// <summary>
        /// The Tax Code 2 assigned for the Line Item, based on the Tax Setting.
        /// </summary>
        /// <value>The Tax Code 2 assigned for the Line Item, based on the Tax Setting.</value>
        [DataMember(Name = "TaxCode2", EmitDefaultValue = false)]
        public string TaxCode2 { get; set; }

        /// <summary>
        /// The Tax Code 3 assigned for the Line Item, based on the Tax Setting.
        /// </summary>
        /// <value>The Tax Code 3 assigned for the Line Item, based on the Tax Setting.</value>
        [DataMember(Name = "TaxCode3", EmitDefaultValue = false)]
        public string TaxCode3 { get; set; }

        /// <summary>
        /// The Tax Code 4 assigned for the Line Item, based on the Tax Setting.
        /// </summary>
        /// <value>The Tax Code 4 assigned for the Line Item, based on the Tax Setting.</value>
        [DataMember(Name = "TaxCode4", EmitDefaultValue = false)]
        public string TaxCode4 { get; set; }

        /// <summary>
        /// The code for the measurement unit used to quantify the good or service. Use GET /invoice/localizeddata to look up codes and descriptions.
        /// </summary>
        /// <value>The code for the measurement unit used to quantify the good or service. Use GET /invoice/localizeddata to look up codes and descriptions.</value>
        [DataMember(Name = "UnitOfMeasure", EmitDefaultValue = false)]
        public string UnitOfMeasure { get; set; }

        /// <summary>
        /// The cost for a single unit of the line item good or service.
        /// </summary>
        /// <value>The cost for a single unit of the line item good or service.</value>
        [DataMember(Name = "UnitPrice", EmitDefaultValue = false)]
        public string UnitPrice { get; set; }

        /// <summary>
        /// The amount of VAT 1 included in the line item total.
        /// </summary>
        /// <value>The amount of VAT 1 included in the line item total.</value>
        [DataMember(Name = "VatAmount", EmitDefaultValue = false)]
        public string VatAmount { get; set; }

        /// <summary>
        /// The amount of VAT 4 included in the line item total.
        /// </summary>
        /// <value>The amount of VAT 4 included in the line item total.</value>
        [DataMember(Name = "VatAmountFour", EmitDefaultValue = false)]
        public string VatAmountFour { get; set; }

        /// <summary>
        /// The amount of VAT 3 included in the line item total.
        /// </summary>
        /// <value>The amount of VAT 3 included in the line item total.</value>
        [DataMember(Name = "VatAmountThree", EmitDefaultValue = false)]
        public string VatAmountThree { get; set; }

        /// <summary>
        /// The amount of VAT 2 included in the line item total.
        /// </summary>
        /// <value>The amount of VAT 2 included in the line item total.</value>
        [DataMember(Name = "VatAmountTwo", EmitDefaultValue = false)]
        public string VatAmountTwo { get; set; }

        /// <summary>
        /// The VAT rate 1 applied to the net line item total.
        /// </summary>
        /// <value>The VAT rate 1 applied to the net line item total.</value>
        [DataMember(Name = "VatRate", EmitDefaultValue = false)]
        public string VatRate { get; set; }

        /// <summary>
        /// The VAT rate 4 applied to the net line item total.
        /// </summary>
        /// <value>The VAT rate 4 applied to the net line item total.</value>
        [DataMember(Name = "VatRateFour", EmitDefaultValue = false)]
        public string VatRateFour { get; set; }

        /// <summary>
        /// The VAT rate 3 applied to the net line item total.
        /// </summary>
        /// <value>The VAT rate 3 applied to the net line item total.</value>
        [DataMember(Name = "VatRateThree", EmitDefaultValue = false)]
        public string VatRateThree { get; set; }

        /// <summary>
        /// The VAT rate 2 applied to the net line item total.
        /// </summary>
        /// <value>The VAT rate 2 applied to the net line item total.</value>
        [DataMember(Name = "VatRateTwo", EmitDefaultValue = false)]
        public string VatRateTwo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentRequestLineItemPut {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Allocations: ").Append(Allocations).Append("\n");
            sb.Append("  AmountWithoutVat: ").Append(AmountWithoutVat).Append("\n");
            sb.Append("  Custom01: ").Append(Custom01).Append("\n");
            sb.Append("  Custom02: ").Append(Custom02).Append("\n");
            sb.Append("  Custom03: ").Append(Custom03).Append("\n");
            sb.Append("  Custom04: ").Append(Custom04).Append("\n");
            sb.Append("  Custom05: ").Append(Custom05).Append("\n");
            sb.Append("  Custom06: ").Append(Custom06).Append("\n");
            sb.Append("  Custom07: ").Append(Custom07).Append("\n");
            sb.Append("  Custom08: ").Append(Custom08).Append("\n");
            sb.Append("  Custom09: ").Append(Custom09).Append("\n");
            sb.Append("  Custom10: ").Append(Custom10).Append("\n");
            sb.Append("  Custom11: ").Append(Custom11).Append("\n");
            sb.Append("  Custom12: ").Append(Custom12).Append("\n");
            sb.Append("  Custom13: ").Append(Custom13).Append("\n");
            sb.Append("  Custom14: ").Append(Custom14).Append("\n");
            sb.Append("  Custom15: ").Append(Custom15).Append("\n");
            sb.Append("  Custom16: ").Append(Custom16).Append("\n");
            sb.Append("  Custom17: ").Append(Custom17).Append("\n");
            sb.Append("  Custom18: ").Append(Custom18).Append("\n");
            sb.Append("  Custom19: ").Append(Custom19).Append("\n");
            sb.Append("  Custom20: ").Append(Custom20).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ExpenseTypeCode: ").Append(ExpenseTypeCode).Append("\n");
            sb.Append("  ItemCode: ").Append(ItemCode).Append("\n");
            sb.Append("  LineItemID: ").Append(LineItemID).Append("\n");
            sb.Append("  PurchaseOrderNumber: ").Append(PurchaseOrderNumber).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  ShipFromPostalCode: ").Append(ShipFromPostalCode).Append("\n");
            sb.Append("  ShipToPostalCode: ").Append(ShipToPostalCode).Append("\n");
            sb.Append("  SupplierPartId: ").Append(SupplierPartId).Append("\n");
            sb.Append("  Tax: ").Append(Tax).Append("\n");
            sb.Append("  TaxCode: ").Append(TaxCode).Append("\n");
            sb.Append("  TaxCode2: ").Append(TaxCode2).Append("\n");
            sb.Append("  TaxCode3: ").Append(TaxCode3).Append("\n");
            sb.Append("  TaxCode4: ").Append(TaxCode4).Append("\n");
            sb.Append("  UnitOfMeasure: ").Append(UnitOfMeasure).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("  VatAmountFour: ").Append(VatAmountFour).Append("\n");
            sb.Append("  VatAmountThree: ").Append(VatAmountThree).Append("\n");
            sb.Append("  VatAmountTwo: ").Append(VatAmountTwo).Append("\n");
            sb.Append("  VatRate: ").Append(VatRate).Append("\n");
            sb.Append("  VatRateFour: ").Append(VatRateFour).Append("\n");
            sb.Append("  VatRateThree: ").Append(VatRateThree).Append("\n");
            sb.Append("  VatRateTwo: ").Append(VatRateTwo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentRequestLineItemPut);
        }

        /// <summary>
        /// Returns true if PaymentRequestLineItemPut instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentRequestLineItemPut to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentRequestLineItemPut input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) &&
                (
                    this.Allocations == input.Allocations ||
                    (this.Allocations != null &&
                    this.Allocations.Equals(input.Allocations))
                ) &&
                (
                    this.AmountWithoutVat == input.AmountWithoutVat ||
                    (this.AmountWithoutVat != null &&
                    this.AmountWithoutVat.Equals(input.AmountWithoutVat))
                ) &&
                (
                    this.Custom01 == input.Custom01 ||
                    (this.Custom01 != null &&
                    this.Custom01.Equals(input.Custom01))
                ) &&
                (
                    this.Custom02 == input.Custom02 ||
                    (this.Custom02 != null &&
                    this.Custom02.Equals(input.Custom02))
                ) &&
                (
                    this.Custom03 == input.Custom03 ||
                    (this.Custom03 != null &&
                    this.Custom03.Equals(input.Custom03))
                ) &&
                (
                    this.Custom04 == input.Custom04 ||
                    (this.Custom04 != null &&
                    this.Custom04.Equals(input.Custom04))
                ) &&
                (
                    this.Custom05 == input.Custom05 ||
                    (this.Custom05 != null &&
                    this.Custom05.Equals(input.Custom05))
                ) &&
                (
                    this.Custom06 == input.Custom06 ||
                    (this.Custom06 != null &&
                    this.Custom06.Equals(input.Custom06))
                ) &&
                (
                    this.Custom07 == input.Custom07 ||
                    (this.Custom07 != null &&
                    this.Custom07.Equals(input.Custom07))
                ) &&
                (
                    this.Custom08 == input.Custom08 ||
                    (this.Custom08 != null &&
                    this.Custom08.Equals(input.Custom08))
                ) &&
                (
                    this.Custom09 == input.Custom09 ||
                    (this.Custom09 != null &&
                    this.Custom09.Equals(input.Custom09))
                ) &&
                (
                    this.Custom10 == input.Custom10 ||
                    (this.Custom10 != null &&
                    this.Custom10.Equals(input.Custom10))
                ) &&
                (
                    this.Custom11 == input.Custom11 ||
                    (this.Custom11 != null &&
                    this.Custom11.Equals(input.Custom11))
                ) &&
                (
                    this.Custom12 == input.Custom12 ||
                    (this.Custom12 != null &&
                    this.Custom12.Equals(input.Custom12))
                ) &&
                (
                    this.Custom13 == input.Custom13 ||
                    (this.Custom13 != null &&
                    this.Custom13.Equals(input.Custom13))
                ) &&
                (
                    this.Custom14 == input.Custom14 ||
                    (this.Custom14 != null &&
                    this.Custom14.Equals(input.Custom14))
                ) &&
                (
                    this.Custom15 == input.Custom15 ||
                    (this.Custom15 != null &&
                    this.Custom15.Equals(input.Custom15))
                ) &&
                (
                    this.Custom16 == input.Custom16 ||
                    (this.Custom16 != null &&
                    this.Custom16.Equals(input.Custom16))
                ) &&
                (
                    this.Custom17 == input.Custom17 ||
                    (this.Custom17 != null &&
                    this.Custom17.Equals(input.Custom17))
                ) &&
                (
                    this.Custom18 == input.Custom18 ||
                    (this.Custom18 != null &&
                    this.Custom18.Equals(input.Custom18))
                ) &&
                (
                    this.Custom19 == input.Custom19 ||
                    (this.Custom19 != null &&
                    this.Custom19.Equals(input.Custom19))
                ) &&
                (
                    this.Custom20 == input.Custom20 ||
                    (this.Custom20 != null &&
                    this.Custom20.Equals(input.Custom20))
                ) &&
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) &&
                (
                    this.ExpenseTypeCode == input.ExpenseTypeCode ||
                    (this.ExpenseTypeCode != null &&
                    this.ExpenseTypeCode.Equals(input.ExpenseTypeCode))
                ) &&
                (
                    this.ItemCode == input.ItemCode ||
                    (this.ItemCode != null &&
                    this.ItemCode.Equals(input.ItemCode))
                ) &&
                (
                    this.LineItemID == input.LineItemID ||
                    (this.LineItemID != null &&
                    this.LineItemID.Equals(input.LineItemID))
                ) &&
                (
                    this.PurchaseOrderNumber == input.PurchaseOrderNumber ||
                    (this.PurchaseOrderNumber != null &&
                    this.PurchaseOrderNumber.Equals(input.PurchaseOrderNumber))
                ) &&
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                ) &&
                (
                    this.ShipFromPostalCode == input.ShipFromPostalCode ||
                    (this.ShipFromPostalCode != null &&
                    this.ShipFromPostalCode.Equals(input.ShipFromPostalCode))
                ) &&
                (
                    this.ShipToPostalCode == input.ShipToPostalCode ||
                    (this.ShipToPostalCode != null &&
                    this.ShipToPostalCode.Equals(input.ShipToPostalCode))
                ) &&
                (
                    this.SupplierPartId == input.SupplierPartId ||
                    (this.SupplierPartId != null &&
                    this.SupplierPartId.Equals(input.SupplierPartId))
                ) &&
                (
                    this.Tax == input.Tax ||
                    (this.Tax != null &&
                    this.Tax.Equals(input.Tax))
                ) &&
                (
                    this.TaxCode == input.TaxCode ||
                    (this.TaxCode != null &&
                    this.TaxCode.Equals(input.TaxCode))
                ) &&
                (
                    this.TaxCode2 == input.TaxCode2 ||
                    (this.TaxCode2 != null &&
                    this.TaxCode2.Equals(input.TaxCode2))
                ) &&
                (
                    this.TaxCode3 == input.TaxCode3 ||
                    (this.TaxCode3 != null &&
                    this.TaxCode3.Equals(input.TaxCode3))
                ) &&
                (
                    this.TaxCode4 == input.TaxCode4 ||
                    (this.TaxCode4 != null &&
                    this.TaxCode4.Equals(input.TaxCode4))
                ) &&
                (
                    this.UnitOfMeasure == input.UnitOfMeasure ||
                    (this.UnitOfMeasure != null &&
                    this.UnitOfMeasure.Equals(input.UnitOfMeasure))
                ) &&
                (
                    this.UnitPrice == input.UnitPrice ||
                    (this.UnitPrice != null &&
                    this.UnitPrice.Equals(input.UnitPrice))
                ) &&
                (
                    this.VatAmount == input.VatAmount ||
                    (this.VatAmount != null &&
                    this.VatAmount.Equals(input.VatAmount))
                ) &&
                (
                    this.VatAmountFour == input.VatAmountFour ||
                    (this.VatAmountFour != null &&
                    this.VatAmountFour.Equals(input.VatAmountFour))
                ) &&
                (
                    this.VatAmountThree == input.VatAmountThree ||
                    (this.VatAmountThree != null &&
                    this.VatAmountThree.Equals(input.VatAmountThree))
                ) &&
                (
                    this.VatAmountTwo == input.VatAmountTwo ||
                    (this.VatAmountTwo != null &&
                    this.VatAmountTwo.Equals(input.VatAmountTwo))
                ) &&
                (
                    this.VatRate == input.VatRate ||
                    (this.VatRate != null &&
                    this.VatRate.Equals(input.VatRate))
                ) &&
                (
                    this.VatRateFour == input.VatRateFour ||
                    (this.VatRateFour != null &&
                    this.VatRateFour.Equals(input.VatRateFour))
                ) &&
                (
                    this.VatRateThree == input.VatRateThree ||
                    (this.VatRateThree != null &&
                    this.VatRateThree.Equals(input.VatRateThree))
                ) &&
                (
                    this.VatRateTwo == input.VatRateTwo ||
                    (this.VatRateTwo != null &&
                    this.VatRateTwo.Equals(input.VatRateTwo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.Allocations != null)
                    hashCode = hashCode * 59 + this.Allocations.GetHashCode();
                if (this.AmountWithoutVat != null)
                    hashCode = hashCode * 59 + this.AmountWithoutVat.GetHashCode();
                if (this.Custom01 != null)
                    hashCode = hashCode * 59 + this.Custom01.GetHashCode();
                if (this.Custom02 != null)
                    hashCode = hashCode * 59 + this.Custom02.GetHashCode();
                if (this.Custom03 != null)
                    hashCode = hashCode * 59 + this.Custom03.GetHashCode();
                if (this.Custom04 != null)
                    hashCode = hashCode * 59 + this.Custom04.GetHashCode();
                if (this.Custom05 != null)
                    hashCode = hashCode * 59 + this.Custom05.GetHashCode();
                if (this.Custom06 != null)
                    hashCode = hashCode * 59 + this.Custom06.GetHashCode();
                if (this.Custom07 != null)
                    hashCode = hashCode * 59 + this.Custom07.GetHashCode();
                if (this.Custom08 != null)
                    hashCode = hashCode * 59 + this.Custom08.GetHashCode();
                if (this.Custom09 != null)
                    hashCode = hashCode * 59 + this.Custom09.GetHashCode();
                if (this.Custom10 != null)
                    hashCode = hashCode * 59 + this.Custom10.GetHashCode();
                if (this.Custom11 != null)
                    hashCode = hashCode * 59 + this.Custom11.GetHashCode();
                if (this.Custom12 != null)
                    hashCode = hashCode * 59 + this.Custom12.GetHashCode();
                if (this.Custom13 != null)
                    hashCode = hashCode * 59 + this.Custom13.GetHashCode();
                if (this.Custom14 != null)
                    hashCode = hashCode * 59 + this.Custom14.GetHashCode();
                if (this.Custom15 != null)
                    hashCode = hashCode * 59 + this.Custom15.GetHashCode();
                if (this.Custom16 != null)
                    hashCode = hashCode * 59 + this.Custom16.GetHashCode();
                if (this.Custom17 != null)
                    hashCode = hashCode * 59 + this.Custom17.GetHashCode();
                if (this.Custom18 != null)
                    hashCode = hashCode * 59 + this.Custom18.GetHashCode();
                if (this.Custom19 != null)
                    hashCode = hashCode * 59 + this.Custom19.GetHashCode();
                if (this.Custom20 != null)
                    hashCode = hashCode * 59 + this.Custom20.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ExpenseTypeCode != null)
                    hashCode = hashCode * 59 + this.ExpenseTypeCode.GetHashCode();
                if (this.ItemCode != null)
                    hashCode = hashCode * 59 + this.ItemCode.GetHashCode();
                if (this.LineItemID != null)
                    hashCode = hashCode * 59 + this.LineItemID.GetHashCode();
                if (this.PurchaseOrderNumber != null)
                    hashCode = hashCode * 59 + this.PurchaseOrderNumber.GetHashCode();
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                if (this.ShipFromPostalCode != null)
                    hashCode = hashCode * 59 + this.ShipFromPostalCode.GetHashCode();
                if (this.ShipToPostalCode != null)
                    hashCode = hashCode * 59 + this.ShipToPostalCode.GetHashCode();
                if (this.SupplierPartId != null)
                    hashCode = hashCode * 59 + this.SupplierPartId.GetHashCode();
                if (this.Tax != null)
                    hashCode = hashCode * 59 + this.Tax.GetHashCode();
                if (this.TaxCode != null)
                    hashCode = hashCode * 59 + this.TaxCode.GetHashCode();
                if (this.TaxCode2 != null)
                    hashCode = hashCode * 59 + this.TaxCode2.GetHashCode();
                if (this.TaxCode3 != null)
                    hashCode = hashCode * 59 + this.TaxCode3.GetHashCode();
                if (this.TaxCode4 != null)
                    hashCode = hashCode * 59 + this.TaxCode4.GetHashCode();
                if (this.UnitOfMeasure != null)
                    hashCode = hashCode * 59 + this.UnitOfMeasure.GetHashCode();
                if (this.UnitPrice != null)
                    hashCode = hashCode * 59 + this.UnitPrice.GetHashCode();
                if (this.VatAmount != null)
                    hashCode = hashCode * 59 + this.VatAmount.GetHashCode();
                if (this.VatAmountFour != null)
                    hashCode = hashCode * 59 + this.VatAmountFour.GetHashCode();
                if (this.VatAmountThree != null)
                    hashCode = hashCode * 59 + this.VatAmountThree.GetHashCode();
                if (this.VatAmountTwo != null)
                    hashCode = hashCode * 59 + this.VatAmountTwo.GetHashCode();
                if (this.VatRate != null)
                    hashCode = hashCode * 59 + this.VatRate.GetHashCode();
                if (this.VatRateFour != null)
                    hashCode = hashCode * 59 + this.VatRateFour.GetHashCode();
                if (this.VatRateThree != null)
                    hashCode = hashCode * 59 + this.VatRateThree.GetHashCode();
                if (this.VatRateTwo != null)
                    hashCode = hashCode * 59 + this.VatRateTwo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
